services:
  barf:
    build: .
    volumes:
      - .:/gem
      - bundle_cache:/usr/local/bundle
    environment:
      - COLORTERM=${COLORTERM:-}
      - TERM=${TERM:-xterm-256color}
    stdin_open: true
    tty: true

volumes:
  bundle_cache:
